services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/static:/usr/share/nginx/html/static:ro
    depends_on:
      - frontend

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb

  backend:
    build: backend/
    volumes:
      - ./nginx/certs:/app/certs:ro
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - DEBUG_MODE=${DEBUG_MODE}

  frontend:
    build: frontend/
    volumes:
      - ./nginx/certs:/app/certs:rw
      - ./frontend/views:/app/views:rw
    depends_on:
      - backend
    environment:
      - SESSION_KEYS=${SESSION_KEYS}
      - DEBUG_MODE=${DEBUG_MODE}

volumes:
  mongo-db:
  mongo-config: