services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/static:/usr/share/nginx/html/static:ro
    depends_on:
      - frontend

  backend:
    build: backend/
    volumes:
      - ./nginx/certs:/app/certs:ro

  frontend:
    build: frontend/
    volumes:
      - ./nginx/certs:/app/certs:rw
      - ./frontend/views:/app/views:rw
    depends_on:
      - backend
    environment:
      - SESSION_KEYS=${SESSION_KEYS}